name = "fieldkit-api"
main = "worker/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "fieldkit-db"
database_id = "476cb614-63c0-44b3-968c-f45f73ff58d0"
